-- Write a query to display the list of bus numbers and names where the source and destination of a bus is the destination and source of another bus.
-- Display the unique records in ascending order by bus_no.

SELECT DISTINCT s1.bus_no,
    b.bus_name
FROM schedule s1
    INNER JOIN schedule s2 ON s1.source = s2.destination
    AND s1.destination = s2.source
    INNER JOIN buses b ON s1.bus_no = b.bus_no
ORDER BY s1.bus_no;

-- Write a query to display the unique user name and their city who have booked their tickets not by using the 'HDFC' bank for any of the bookings.
-- Sort the result based on the user name.

SELECT DISTINCT u.name, u.address FROM users u
JOIN bookingdetails b ON b.user_id = u.user_id
WHERE u.user_id NO IN 
( SELECT user_id FROM bookingdetails WHERE name='HDFC')
ORDER BY u.name;

-- Write a query to display the user name and password.
-- Password should be generated by concatenating the first three characters of the user name and the first three numbers of the phone number attribute.
-- Give an alias name as PASSWORD.
-- Sort the result based on the user name.

SELECT name, CONCAT(SUBSTR(NAME,1,3), SUBSTR(PHNO,1,3)) AS password
FROM users 
ORDER BY name;

-- Write a query to display the username and password of all customers.
-- Give an alias name as USERNAME and PASSWORD.
-- Sort the result based on the Username in ascending order.

SELECT CONCAT(cust_name,cust_id) AS USERNAME, CONCAT(SUBSTR(cust_name,1,3),SUBSTR(cust_phone,-4,4)) as PASSWORD
FROM customer 
ORDER BY USER NAME;
